Fixes and render restructurization
Southclaws/progress2 pull request #56
Opened 2023-04-16 12:09 UTC by MuthaX

1) Bar's geometry is now in separated procedure because of same computations exist in different places (set value and render).
2) Fixed rare & special bugs that goes from textdraw recreation (read comments in commits and code).
There also different solutions for SAMP & OMP.
3) 1+2 fixes also SetValue for directions BAR_DIRECTION_HORIZONTAL_FROM_0, BAR_DIRECTION_VERTICAL_FROM_0 (because originally there was only computation for original non _FROM_0 direction.
4) First call of progress bar creation causes to self initialization of this system.
5) It is now possible to define any other maximum number of bars per player externally. Its also validating user defined MAX_PLAYER_BARS.

2023-05-01 11:31 UTC, Southclaws commented on progress2.inc
> +	PlayerText:pbar_unused	// for 16-byte alignment
this probably isn't necessary in Pawn

2023-05-01 11:35 UTC, Southclaws requested changes

2023-05-01 11:35 UTC, Southclaws commented on progress2.inc
> +		boundry[E_PROGRESSBAR_BOUNDRY],
```suggestion
		boundary[E_PROGRESSBAR_BOUNDRY],
```

2023-05-01 11:35 UTC, Southclaws commented on progress2.inc
> +		} else {	// Rare case: main/value textdraw was created UNDER(win lower ID than) filler/background textdraw -> recreate whole bar again.
```suggestion
		} else {	// Rare case: main/value textdraw was created UNDER(with lower ID than) filler/background textdraw -> recreate whole bar again.
```

not sure if intended word?

2023-05-04 19:53 UTC, MuthaX commented on progress2.inc
> +		boundry[E_PROGRESSBAR_BOUNDRY],
done

2023-05-04 19:59 UTC, MuthaX commented on progress2.inc
> +		} else {	// Rare case: main/value textdraw was created UNDER(win lower ID than) filler/background textdraw -> recreate whole bar again.
you are right

2023-05-04 20:02 UTC, MuthaX commented on progress2.inc
> +	PlayerText:pbar_unused	// for 16-byte alignment
ok, removed

2023-05-06 19:54 UTC, Zorono approved these changes

2023-05-06 19:55 UTC, Zorono commented on progress2.inc
> +	{	// Textdraw set position not found. Set with recreation.
what is the use of these brackets ??

2023-05-07 09:14 UTC, MuthaX commented on progress2.inc
> +	{	// Textdraw set position not found. Set with recreation.
highlight block of code

2023-05-18 12:48 UTC, Southclaws approved these changes
Thanks for these updates!

2023-05-18 12:48 UTC, merged